
name: Update JS Bundle

# Controls when the action will run. 
on:
  repository_dispatch:
    types: [update]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: Fuukei/Sakurairo_Scripts
          path: ./script

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5  
        
      - name: Cache node modules
        uses: actions/cache@v2
        env:
         cache-name: cache-node-modules
        with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
         path: ~/.npm
         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-   
          
      - name: Install dependencies
        run: |
             cd $GITHUB_WORKSPACE/script
             npm i
        
      - name: Build bundle
        run: |
             cd $GITHUB_WORKSPACE/script
             npm run build
        
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: ./theme
        
      - name: Copy files
        run: |
             cp $GITHUB_WORKSPACE/script/dist/sakura-app.js $GITHUB_WORKSPACE/theme/js/sakura-app.js
             cp $GITHUB_WORKSPACE/script/dist/sakura-app.js.map $GITHUB_WORKSPACE/theme/js/sakura-app.js.map
             cp $GITHUB_WORKSPACE/script/dist/sakura-app.js.LICENSE.txt $GITHUB_WORKSPACE/theme/js/sakura-app.js.LICENSE.txt
      
      - name: Make Commit Message （Last Commit）
        run:  |
              cd $GITHUB_WORKSPACE/script
              echo $(git show -s --format=format:"last commit: %h by %aN,%n%B | %ci") > _commits
              
      - name: Export to env
        uses: pCYSl5EDgo/cat@master
        id: commits
        with:
          path: ./script/_commits

      - name: Commit
        uses: zwaldowski/git-commit-action@v1
        with:
          commit_message: ${{ steps.commits.outputs.text }}
          working_directory: ./theme
      - run: |
             cd $GITHUB_WORKSPACE/theme
             git push origin
